[tool.poetry]
name = "project-consumer-py"
version = "0.1.0"
description = "Testear que importamos bien la libreria"
authors = ["Lauri"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
